### ISSUE TITLE
[Feature] 레이아웃, 네비게이션 컴포넌트 구현

### ISSUE THREAD

**Issue by hamo-o** [FRONTLINE2024/wow-bamboo-forest#4]
## 배경
- 두 `API` 방식의 장단점을 비교하고 라우팅 방식을 채택합니다.
- 네비게이션 컴포넌트를 구현합니다.

## ✅ TODO

- [x] 라우팅 방식 채택 #2 vs #3
- [x] 네비게이션 컴포넌트 구현
- [x] 레이아웃 컴포넌트 구현
